---

- name: Install Netplan
  become: yes
  apt:
    name: netplan.io
    state: present

- name: Template Netplan config
  become: yes
  template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
  no_log: yes

- name: Run netplan apply
  become: yes
  command: netplan apply
